title: "RDF on Elixir"
description: "Implementation of the Linked Data and Semantic Standards for Elixir"
themeConfig:
  displayAllHeaders: true
  nav:
  - 
    text: "Home"
    link: "/"
  - 
    text: "RDF.ex"
    link: "/rdf-ex/"
  - 
    text: "SPARQL.ex"
    link: "/sparql-ex/"
  - 
    text: "SPARQL.Client"
    link: "/sparql-client/"
  - 
    text: "API Documentation"
    items: 
    - 
      text: "RDF.ex"
      link: "https://hexdocs.pm/rdf/"
    - 
      text: "SPARQL.ex"
      link: "https://hexdocs.pm/sparql/"
    - 
      text: "SPARQL.Client"
      link: "https://hexdocs.pm/sparql_client/"
  sidebar:
  - "/rdf-ex/"
  - "/sparql-ex/"
  - "/sparql-client/"
  repo: marcelotto/rdf-ex
